apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhnmrt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhnmrt
  template:
    metadata:
      labels:
        app: dhnmrt
    spec:
      containers:
      - image: okteto.dev/dhnmrt:latest
        name: dhnmrt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "d71f936f-bca0-4be1-9326-459370130242"
        - name: Vless_Path
          value: "/vl5nb95"
        - name: Vmess_UUID
          value: "d71f936f-bca0-4be1-9326-459370130242"
        - name: Vmess_Path
          value: "/vm66rn7"
        - name: Share_Path
          value: "/v2link"
